//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace healB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicine
    {
        public int medicine_id { get; set; }
        public string name { get; set; }
        public string dosage { get; set; }
        public Nullable<int> time_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public bool is_prescription { get; set; }
    
        public virtual time time { get; set; }
    }
}
