//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace healB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vital
    {
        public int vital_id { get; set; }
        public Nullable<int> systolic { get; set; }
        public Nullable<int> diastolic { get; set; }
        public Nullable<int> heart_rate { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> waist { get; set; }
        public System.DateTime date { get; set; }
    }
}
